### ISSUE TITLE
Automatically detect Yarn as default install-cmd

### ISSUE THREAD

**Issue by michaellopez** [lhaggar/package-change-checker#4]
Hi @lhaggar 

We recently setup a monorepo and use Yarn + Lerna to manage it. We've also moved our Husky config to a separate package to have the same config applied to all our internal projects.

Husky runs `package-change-checker` for us for some git hooks, but right now it defaults to `npm install`. That works great in our usual repositories that use `npm`, but in this (and most likely future) monorepos were we mainly use `yarn` we'd like `package-change-checker` to default to `yarn` if it detects a `yarn.lock` file in the repo root. Would you be willing to accept such a PR?

**Comment by lhaggar** [comment]
Hey @michaellopez 

Interesting idea! Not totally convinced the functionality is needed though. Presumably you've got your Husky config as a `.js` file which you import into each project package? Could you not do something like the following, utilising the custom `install-cmd` arg?

Husky config module:
```javascript
module.exports = (packageManager = 'npm') => ({
  "hooks": {
      "post-merge": `package-change-checker --install-cmd=\"${packageManager} install --pure-lockfile\" HEAD@{1} HEAD`,
      "post-checkout": `package-change-checker --install-cmd=\"${packageManager} install --pure-lockfile\" HEAD@{1} HEAD`,
    }
})
```

Project .huskyrc.js:
```javascript
module.exports = require('husky-package-config')('yarn');
```

**Comment by michaellopez** [comment]
@lhaggar Nice idea, I'll try that! We generate our ` .huskyrc.js` in `postinstall` so we can do the check for yarn there and generate a different ` .huskyrc.js` depending on the check.

Care to explain `--pure-lockfile\" HEAD@{1} HEAD?` Feels like a protip I haven't seen or heard that I want to learn 😄

**Comment by lhaggar** [comment]
Ah, using the `pure-lockfile` arg to make the lock file read only. We were experiencing the lock file getting updated sometimes on the install. The `HEAD@{1}` is used rather than `ORIG_HEAD` as the latter only points to the previous HEAD on significant change, so changing branches for example, wasn't triggering the check.

**Comment by michaellopez** [comment]
Thanks for the reply!
